### ISSUE TITLE
Explore patent databases

### ISSUE THREAD

**Issue by Gunjan-Sharma** [mcandrews17/wibd-ls1#6]
Take 3-5 samples and perform manual search to see the results. What is the search criteria, what are the output fields.
Is there an API to systematically search the patent databases.

There are 2 databases to explore.

**Comment by Gunjan-Sharma** [comment]
Sossena - Can you add the findings for the two databases? Are we saying we'll forget about the second database and just go with the WIPO one? I'll let you decide whether this is ready to be closed.

**Comment by snegussie** [comment]
Findings:
1.  WIPO allows searching by patent number and year.
2. Espacenet requires keywords from abstract or title to do any search.  Since we don't have this information and can't extract it from the scanned images, we can't use this database.

See attached file for screen shots of search parameters and results from each Patent database.  

[Patent Databases -  Search Results.docx](https://github.com/mcandrews17/wibd-ls1/files/2338493/Patent.Databases.-.Search.Results.docx)
