### ISSUE TITLE
Explore Google Cloud Vision API in Batch Mode

### ISSUE THREAD

**Issue by vnorekyan** [mcandrews17/wibd-ls1#9]
Go through all of the images on S3 and dump out the json.

**Comment by Gunjan-Sharma** [comment]
On Cloud Vision, you can use the annotate request for batch processing.
If you are using Google Client - installing cloud vision on your laptop and running locally, then you use 
https://googlecloudplatform.github.io/google-cloud-python/latest/vision/gapic/v1/api.html, annotate_image. Click on AnnotateImageRequest and it will take you to the request object in which you specify the feature you want, in our case its TEXT_DETECTION
Pseudococde will be something like
while image in imagestore
{
image = get next image path from Storage bucket
annotateimagerequest = json structure with the image path and feature is Text Detection
response = imageannotatorclient.annotate_image(annotateimagerequest)
}

Alternatively, you could try the 'async batch annotate image' as well but we can worry about that if we decide to go with the vision API.

Another option is to use the REST API end point, where you will do the same thing but call the rest end point instead of the method on the client API.

Hope this helps.

**Comment by Gunjan-Sharma** [comment]
Google cloud functions have meagre support for Python, you'd need Node.js. If you're not comfortable, it may be better to install the SDK and use the client Python libraries
https://googlecloudplatform.github.io/google-cloud-python/latest/vision/index.html

**Comment by Gunjan-Sharma** [comment]
Vision provided 80% accuracy (29/97 were wrong). Going with Rekognition + Tesseract and sticking with AWS.
